[package]
name = "spiral_scan"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "spiral_scan"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.20.2"
numpy = "0.20.0"
